name: Build Python Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # BUILD STEP FOR WINDOWS (Uses semicolon ; for data path)
      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: >
          pyinstaller --onefile --name my_app_${{ runner.os }} 
          --copy-metadata streamlit 
          --collect-all streamlit 
          --collect-all imageio 
          --collect-all scipy 
          --collect-all matplotlib 
          --add-data "app_Doping.py;." 
          run_app.py

      # BUILD STEP FOR MAC & LINUX (Uses colon : for data path)
      - name: Build with PyInstaller (Mac/Linux)
        if: runner.os != 'Windows'
        run: >
          pyinstaller --onefile --name my_app_${{ runner.os }} 
          --copy-metadata streamlit 
          --collect-all streamlit 
          --collect-all imageio 
          --collect-all scipy 
          --collect-all matplotlib 
          --add-data "app_Doping.py:." 
          run_app.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ runner.os }}
          path: dist/*
          retention-days: 5
